export type Buildprint = {
  slug: string;
  title: string;
  creator: string;
  category: string;
  stack: string[];
  difficulty: 'Small' | 'Medium' | 'Advanced';
  summary: string;
  promise: string;
  imageTone: string;
  includes: string[];
  risks: string[];
  files: string[];
  checks: string[];
  copyPrompt: string;
  methodology?: string[];
  runtimeSpine?: string[];
  proofNotes?: string[];
  githubUrl: string;
  manifestUrl: string;
};

export const buildprints: Buildprint[] = [
  {
    slug: "auth-teams-rbac-os",
    title: "Auth, Teams & RBAC OS",
    creator: "Agent Buildprint",
    category: "Feature",
    stack: ["Auth", "Teams", "RBAC", "Multi-tenant SaaS", "Audit logs"],
    difficulty: "Advanced",
    summary: "Secure team accounts, memberships, roles, permissions, invites, audit logs, and tenant isolation around an existing auth provider.",
    promise: "Add Auth, Teams & RBAC without letting an agent rip out existing auth, fake frontend-only permissions, or miss tenant isolation.",
    imageTone: "from-violet-400/20 via-fuchsia-400/10 to-cyan-500/20",
    includes: ["Auth forensics", "Tenant boundary map", "Permission engine", "Invite lifecycle", "Audit log", "Offline TypeScript proof", "Target-app conformance kit"],
    risks: ["Frontend-only authorization", "Cross-tenant data leaks", "Self-escalation or last-owner loss"],
    files: ["BUILDPRINT.md", "SPEC.md", "CONTRACTS.md", "RBAC_MATRIX.md", "API_ROUTES.md", "UI_FLOWS.md", "TEST_MATRIX.md", "proof/src/index.ts", "proof/test/rbac.test.ts", "conformance/src/adapter-contract.ts", "conformance/test/auth-rbac.conformance.test.ts", "README.md", "PLAN.md", "VALIDATION_TEMPLATE.md", "checks/acceptance.md"],
    checks: ["Phase 00 forensics must complete first", "Permission engine denies by default", "Every team-scoped route has direct API auth tests", "Invites and role changes emit redacted audit events", "Offline proof harness is included and testable", "Target-app conformance suite must pass against a real adapter or record blockers"],
    copyPrompt: "Use the Agent Buildprint: Auth, Teams & RBAC OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/auth-teams-rbac-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine. Do Phase 00 auth forensics and tenant research before coding. Reuse existing auth by default, enforce permissions server-side, and do not claim completion while any team-scoped route lacks direct authorization tests.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/auth-teams-rbac-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/auth-teams-rbac-os/package.json",
  },
  {
    slug: "ai-influencer-os",
    title: "OpenClaw AI Influencer OS",
    creator: "Agent Buildprint",
    category: "Product OS",
    stack: ["OpenClaw", "Telegram", "Wavespeed", "OpenRouter", "Docker"],
    difficulty: "Advanced",
    summary: "Persona memory, social drafting, image generation, approval gates, and secured browser publishing handoff for an AI influencer runtime.",
    promise: "Bootstrap a full OpenClaw-based AI Influencer OS without letting an agent collapse it into a generic chatbot or scheduler.",
    imageTone: "from-pink-400/20 via-fuchsia-400/10 to-cyan-500/20",
    includes: ["Persona + memory state", "Wavespeed image workflow", "Grounded social drafts", "Manager audit", "Secured browser handoff"],
    risks: ["Auto-publishing by default", "Unsafe public/private media handling", "Unauthenticated noVNC exposure"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "DEFAULT_PRESET.md", "PLAN.md", "SPEC.md", "TEST_MATRIX.md", "VALIDATION_TEMPLATE.md", "README.md", "checks/acceptance.md"],
    checks: ["Mock tests make no external API calls", "Media policy gates return structured blocks", "Publishing defaults to approval/manual mode", "Runtime command and files are present"],
    copyPrompt: "Use the Agent Buildprint: OpenClaw AI Influencer OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/ai-influencer-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/ai-influencer-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/ai-influencer-os/package.json",
  },
  {
    slug: "automated-ai-blog-os",
    title: "Automated AI Blog OS",
    creator: "Agent Buildprint",
    category: "Product OS",
    stack: ["Astro/MDX", "Markdown", "SEO", "Approval queue", "Scheduler"],
    difficulty: "Advanced",
    summary: "Research scanning, idea scoring, content memory, draft generation, SEO validation, approval queue, and scheduled publishing.",
    promise: "Give a coding agent the full operating contract for a useful AI blog pipeline that does not skip SEO, approval, or stale-content audits.",
    imageTone: "from-lime-400/20 via-emerald-400/10 to-cyan-500/20",
    includes: ["Research scanner", "Idea scorer", "Content memory", "SEO validator", "Approval queue"],
    risks: ["Publishing without approval", "Unsupported claims", "SEO/build checks skipped"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "DEFAULT_PRESET.md", "PLAN.md", "SPEC.md", "TEST_MATRIX.md", "VALIDATION_TEMPLATE.md", "README.md", "checks/acceptance.md"],
    checks: ["Drafts cite source/evidence state", "SEO/build validator runs before publish", "Approval gate blocks external publishing", "Manager audit catches stale work"],
    copyPrompt: "Use the Agent Buildprint: Automated AI Blog OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/automated-ai-blog-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/automated-ai-blog-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/automated-ai-blog-os/package.json",
  },
  {
    slug: "buildprint-mapper-os",
    title: "Buildprint Mapper OS",
    creator: "Agent Buildprint",
    category: "Quality",
    stack: ["Any repo", "Phase-flow replay", "Evidence ledger", "Fresh-agent evals"],
    difficulty: "Advanced",
    summary: "Map an existing repo into an executable Buildprint packet with phase-flow replay, schema-valid evidence, review contracts, and fresh-agent isolation.",
    promise: "Turn a real codebase into a source-independent execution contract so agents build in bounded phases, prove claims honestly, and hand off without source-repo access.",
    imageTone: "from-sky-400/20 via-teal-400/10 to-lime-400/20",
    includes: ["Source census", "Scope selection", "Executable packet spine", "Phase-flow constitution", "Runtime evidence schema", "Architecture/UX/QA review loop", "Fresh-agent replay scorer"],
    risks: ["Secret leakage", "Scope shrink", "Synthetic proof overclaimed", "Provider/browser blockers hidden as success"],
    files: ["BUILDPRINT.md", "METHODOLOGY.md", "EXECUTION_PROTOCOL.md", "CONTRACTS.md", "03-phases/phase-flow.md", "05-evidence/evidence-ledger.schema.json", "scripts/eval-mapper-replay.mjs", "scripts/check-mapper-selected-output.mjs", "evals/selected-output-fixtures/*"],
    checks: ["Every phase starts with implementation grammar", "Runtime evidence rows are schema-valid", "Blocked/synthetic evidence cannot upgrade claims", "No-fake scans require real artifacts", "Architecture/UX/QA reviews answer required headings", "Fresh-agent replay and outcome judge pass or name gaps"],
    methodology: ["Source-independent distillation", "Phase-flow replay", "Bounded team simulation", "Evidence honesty", "Fresh-agent isolation"],
    runtimeSpine: ["01-questions.md", "02-project-setup.md", "03-phases/phase-flow.md", "03-phases/<phase-id>.md", "04-evaluation.md", "05-evidence/evidence-ledger.schema.json", ".buildprint/phase-runs/<phase-id>/proof.md", ".buildprint/evidence/evidence-ledger.jsonl"],
    proofNotes: ["MiroFish map judge: 89, ship-with-notes", "Replay workspace: /tmp/mapper-replay-rDH0JF", "Outcome judge: 0.74, ship-with-notes", "Final flow report: pass true"],
    copyPrompt: "Use the Agent Buildprint: Buildprint Mapper OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/buildprint-mapper-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md plus METHODOLOGY.md as the authority. Generate a source-independent selected-buildprint packet, preserve scope fidelity, require phase-flow execution, read evidence-ledger.schema.json before runtime evidence, write runtime rows only to .buildprint/evidence/evidence-ledger.jsonl, and do not upgrade blocked, synthetic, credential-limited, or browser-limited proof claims.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/buildprint-mapper-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/buildprint-mapper-os/package.json",
  },
  {
    slug: "complete-agent-skills-evaluation-os",
    title: "Complete Agent Skills Evaluation OS",
    creator: "Agent Buildprint",
    category: "Quality",
    stack: ["Node.js", "Fixtures", "Eval harness", "CI"],
    difficulty: "Advanced",
    summary: "Offline deterministic evals for skills, agent setup contracts, commands, hooks, routers, subagents, and workflow rules.",
    promise: "Prove whether an agent setup is installed, discoverable, useful, safe, reproducible, and worth its context cost.",
    imageTone: "from-violet-400/20 via-indigo-400/10 to-cyan-500/20",
    includes: ["Setup snapshot", "Static lint", "Skill unit evals", "Transcript invariants", "Scorecard"],
    risks: ["Live-provider false positives", "Undiscoverable skills", "Unsafe multi-agent execution"],
    files: ["ACTIVATION_EVALS.md", "BUILDPRINT.md", "CONTRACTS.md", "E2E_TASK_BENCH.md", "LOADOUT_INVENTORY.md", "MULTI_AGENT_SAFETY.md", "SAFETY_POLICY.md", "README.md", "SPEC.md", "PLAN.md", "TEST_MATRIX.md", "VALIDATION_TEMPLATE.md", "checks/acceptance.md"],
    checks: ["Offline fixtures only by default", "Scorecard produces evidence", "Process invariants are asserted", "Live adapters require separate acceptance"],
    copyPrompt: "Use the Agent Buildprint: Complete Agent Skills Evaluation OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/complete-agent-skills-evaluation-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/complete-agent-skills-evaluation-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/complete-agent-skills-evaluation-os/package.json",
  },
  {
    slug: "perfect-rag-retrieval-os",
    title: "Perfect RAG / Retrieval OS",
    creator: "Agent Buildprint",
    category: "Workflow OS",
    stack: [
      "Mapper OS v5",
      "Hybrid retrieval",
      "Reranking",
      "Citations",
      "RAG evals"
    ],
    difficulty: "Advanced",
    summary: "Executable Mapper OS phase-flow packet for building a serious RAG/Retrieval OS with corpus contracts, ingestion, chunking, hybrid retrieval, permission filtering, reranking, grounded citations, refusal behavior, traces, and eval gates.",
    promise: "A fresh agent can run the packet from BUILDPRINT.md through phase-flow to implement a permission-safe, citation-grounded retrieval system without reducing the product to vector search plus a prompt.",
    imageTone: "from-blue-400/20 via-cyan-400/10 to-emerald-500/20",
    includes: [
      "BUILDPRINT.md canonical start",
      "01-questions.md alignment gate",
      "02-project-setup.md architecture, team, authority, handoff, AGENTS.md, quality, safety, and phase-start contract",
      "blueprint.yaml executable-blueprint v5 machine contract",
      "03-phases/phase-flow.md orchestration protocol",
      "Four implementation phases with proof gates",
      "04-evaluation.md retrieval, answer, operational, blocker, and claim-upgrade rules",
      "05-evidence seed ledger and runtime evidence schema"
    ],
    risks: [
      "Vector-only false confidence",
      "Hallucinated uncited answers",
      "Permission leakage",
      "Eval-free quality drift",
      "Reranker latency/cost creep",
      "Live provider claims from deterministic proof",
      "Advanced-tech hype without measured gain"
    ],
    files: [
      "BUILDPRINT.md",
      "01-questions.md",
      "02-project-setup.md",
      "blueprint.yaml",
      "03-phases/phase-index.yaml",
      "03-phases/phase-flow.md",
      "04-evaluation.md",
      "05-evidence/evidence-ledger.schema.json",
      "05-evidence/evidence-ledger.jsonl"
    ],
    checks: [
      "Mapper OS selected-output structural check passes",
      "Packet uses BUILDPRINT.md as canonical start",
      "Every phase starts with Mapper OS phase-flow entry grammar",
      "Runtime evidence is separated from packaged seed evidence",
      "Evidence schema blocks missing, blocked, synthetic, partial, sandbox, network-limited, and credential-limited rows from upgrading claims",
      "Publication copy reflects phase-flow methodology rather than legacy proof-only package"
    ],
    copyPrompt: "Use the Perfect RAG / Retrieval OS Buildprint as a Mapper OS phase-flow packet. Start at BUILDPRINT.md, then read 01-questions.md, 02-project-setup.md, blueprint.yaml, 03-phases/phase-index.yaml, 03-phases/phase-flow.md, the active phase file, 04-evaluation.md, and the seed evidence schema. Complete setup before phase work, create .buildprint phase-run artifacts, and append runtime evidence only to .buildprint/evidence/evidence-ledger.jsonl. Implement corpus contracts, ingestion/chunking/indexing, hybrid lexical/sparse plus dense retrieval, fusion/dedupe, permission filtering before context packing, reranking, token-budgeted grounded answers with citations, insufficient-evidence refusal, traces, and eval gates. Use deterministic proof mode unless live providers are explicitly configured and separately proven. Do not call vector-only retrieval complete.",
    methodology: [
      "Setup gate",
      "Phase-flow execution",
      "Runtime evidence ledger",
      "Claim-safe validation"
    ],
    runtimeSpine: [
      "BUILDPRINT.md",
      "01-questions.md",
      "02-project-setup.md",
      "blueprint.yaml",
      "03-phases/phase-index.yaml",
      "03-phases/phase-flow.md",
      "03-phases/<active-phase>.md",
      "04-evaluation.md",
      "05-evidence/evidence-ledger.schema.json",
      ".buildprint/phase-runs/<phase-id>/proof.md",
      ".buildprint/evidence/evidence-ledger.jsonl"
    ],
    proofNotes: [
      "Phase-flow packet with setup gate, role handoffs, proof gates, and evidence honesty.",
      "The packet explicitly rejects vector-only RAG and requires measurable retrieval behavior.",
      "Deterministic proof mode is separated from live embedding, search, reranker, and generator claims.",
      "Tenant/private filtering is a server-side proof gate before context packing and answer generation."
    ],
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/perfect-rag-retrieval-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/perfect-rag-retrieval-os/package.json",
  },
  {
    slug: "portable-ai-shorts-production-studio",
    title: "Portable AI Shorts Production Studio",
    creator: "Agent Buildprint",
    category: "Mapped Project",
    stack: [
      "Product analysis",
      "UGC scripts",
      "Provider adapters",
      "Async jobs",
      "Media composition",
      "Gallery and publish handoff"
    ],
    difficulty: "Advanced",
    summary: "Mapper OS phase-flow Buildprint for a portable AI shorts production studio with product URL/manual input, UGC scripts, deterministic provider adapters, pollable jobs, 1080x1920 MP4 fixture media, private gallery, consent-gated publish handoff, and evidence-honest validation.",
    promise: "A Mapper OS executable packet that preserves the full AI shorts production workflow while keeping provider, media, browser, persistence, gallery, publishing, and security claims tied to phase proof and runtime evidence.",
    imageTone: "from-orange-400/20 via-rose-400/10 to-purple-500/20",
    includes: [
      "BUILDPRINT.md canonical start",
      "01-questions.md AI best-judgment alignment gate",
      "02-project-setup.md with architecture, team model, AGENTS.md plan, safety, gates, and phase start gate",
      "blueprint.yaml executable-blueprint v5 machine contract",
      "03-phases/phase-flow.md orchestration protocol",
      "Five implementation phase files",
      "04-evaluation.md claim upgrade rules",
      "05-evidence/evidence-ledger.schema.json honest evidence schema",
      "Seed-only 05-evidence/evidence-ledger.jsonl",
      "Compatibility docs for specification, contracts, plan, test matrix, validation, and acceptance"
    ],
    risks: [
      "Accidentally implying OpenShorts clone or drop-in replacement parity",
      "Provider/API/live media success overclaiming",
      "Rendering-quality parity overclaiming",
      "Social platform publishing reliability overclaiming",
      "Public gallery exposure without consent and access controls",
      "User likeness, uploaded media, URL egress, and copyright under-specification",
      "In-memory proof storage being misreported as production durability"
    ],
    files: [
      "BUILDPRINT.md",
      "01-questions.md",
      "02-project-setup.md",
      "blueprint.yaml",
      "03-phases/phase-index.yaml",
      "03-phases/phase-flow.md",
      "04-evaluation.md",
      "05-evidence/evidence-ledger.schema.json",
      "05-evidence/evidence-ledger.jsonl"
    ],
    checks: [
      "Mapper OS selected-output spine exists and starts from BUILDPRINT.md",
      "Every phase starts with the required Mapper OS phase implementation heading",
      "Every phase requires phase-flow, .buildprint/next-agent.md, and current project AGENTS.md",
      "02-project-setup.md defines architecture, team operating model, execution authority, delegation, AGENTS.md plan, quality gates, safety, assumptions, and phase start gate",
      "Packaged evidence ledger is seed-only and runtime evidence routes to .buildprint/evidence/evidence-ledger.jsonl",
      "Evidence schema requires artifact_id, type, phase_id, status, source, proves, proof_type, provider_mode, and upgrades_claim",
      "Blocked, missing, synthetic, partial, sandbox-limited, network-limited, credential-limited, or dry-run proof cannot upgrade claims",
      "Browser, provider, media, persistence, billing-free publishing handoff, security, memory/retrieval-adjacent context, and operational boundaries are preserved as explicit contracts"
    ],
    copyPrompt: "Use the Portable AI Shorts Production Studio Buildprint. First bootstrap exact snapshots: agb start https://agent-buildprint.com/buildprints/portable-ai-shorts-production-studio/package.json . If agb is not installed, clone https://github.com/DomEscobar/agent-buildprint and run node agent-buildprint/bin/agb.js start https://agent-buildprint.com/buildprints/portable-ai-shorts-production-studio/package.json . Then read BUILDPRINT.md, 01-questions.md, 02-project-setup.md, blueprint.yaml, 03-phases/phase-index.yaml, 03-phases/phase-flow.md, the active phase file, 04-evaluation.md, and 05-evidence/evidence-ledger.jsonl. Use Mapper OS phase-flow artifacts before implementation and write runtime evidence only to .buildprint/evidence/evidence-ledger.jsonl. Build the full browser AI shorts production studio proof with deterministic mock/no-network providers, pollable jobs, a playable 1080x1920 MP4 fixture, private gallery, consent-gated publish handoff, browser QA, and honest claim boundaries.",
    methodology: [
      "Setup gate",
      "Phase-flow execution",
      "Runtime evidence ledger",
      "Claim-safe validation"
    ],
    runtimeSpine: [
      "BUILDPRINT.md",
      "01-questions.md",
      "02-project-setup.md",
      "blueprint.yaml",
      "03-phases/phase-index.yaml",
      "03-phases/phase-flow.md",
      "03-phases/<active-phase>.md",
      "04-evaluation.md",
      "05-evidence/evidence-ledger.schema.json",
      ".buildprint/phase-runs/<phase-id>/proof.md",
      ".buildprint/evidence/evidence-ledger.jsonl"
    ],
    proofNotes: [
      "Phase-flow executable packet with proof-gated implementation phases.",
      "Seed evidence is separated from runtime proof and blockers cannot upgrade claims.",
      "Default proof uses deterministic no-network adapters; live providers are optional and gated.",
      "OpenShorts-inspired scope is preserved without claiming clone, provider, rendering, or publishing parity."
    ],
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/portable-ai-shorts-production-studio",
    manifestUrl: "https://agent-buildprint.com/buildprints/portable-ai-shorts-production-studio/package.json",
  },
  {
    slug: "portable-durable-agent-graph-runtime",
    title: "Portable Durable Agent Graph Runtime",
    creator: "Agent Buildprint",
    category: "Agent",
    stack: ["TypeScript", "Graph runtime", "Checkpoints", "Streams", "Interrupts"],
    difficulty: "Advanced",
    summary: "Dependency-light runtime for typed state, graph nodes, conditional edges, checkpointing, streaming, interrupts, and resume.",
    promise: "Create a portable LangGraph-like mental model without runtime lock-in or hidden framework dependencies.",
    imageTone: "from-cyan-400/20 via-indigo-400/10 to-purple-500/20",
    includes: ["Typed state schema", "Graph builder", "Checkpoint saver", "Interrupt/resume", "Streaming invoke"],
    risks: ["Fake durability", "Unclear state reducers", "Side effects without checkpoints"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "PARITY_CLAIMS.md", "PLAN.md", "QA_PLAN.md", "README.md", "SOURCE_TRACE.md", "SPEC.md", "TEST_MATRIX.md", "VALIDATION_TEMPLATE.md", "checks/acceptance.md"],
    checks: ["Compile validation catches bad routes", "Checkpoint interfaces are explicit", "Interrupt resume is tested", "No heavyweight graph dependency required"],
    copyPrompt: "Use the Agent Buildprint: Portable Durable Agent Graph Runtime.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/portable-durable-agent-graph-runtime/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/portable-durable-agent-graph-runtime",
    manifestUrl: "https://agent-buildprint.com/buildprints/portable-durable-agent-graph-runtime/package.json",
  },
  {
    slug: "portable-novel-storyboard-pipeline",
    title: "Portable Novel-to-Storyboard Pipeline",
    creator: "Agent Buildprint",
    category: "Product OS",
    stack: ["Story pipeline", "Mock providers", "Storyboard XML", "Canvas QA"],
    difficulty: "Advanced",
    summary: "Import chapters, extract events, adapt scripts, create assets, generate storyboard panels, validate XML, and preview without fake success states.",
    promise: "Build a deterministic novel-to-storyboard pipeline that agents can implement end-to-end before expanding into live providers.",
    imageTone: "from-amber-400/20 via-fuchsia-400/10 to-blue-500/20",
    includes: ["Chapter import", "Event extraction", "ScriptAgent stages", "Asset extraction", "Storyboard validation"],
    risks: ["Malformed XML corrupting state", "Placeholder controls", "Live-provider claims without gates"],
    files: ["AGENT_HANDOFF.md", "AGENT_PROMPT_PACK.md", "ASYNC_JOB_MODEL.md", "BROWSER_QA_SCENARIOS.md", "BUILDPRINT.md", "CONTRACTS.md", "HEAD_TO_FOOT_QA.md", "README.md", "SPEC.md", "PLAN.md", "TEST_MATRIX.md", "VALIDATION_TEMPLATE.md", "checks/acceptance.md"],
    checks: ["Default CI uses mock/no-network providers", "3 fixture chapters complete successfully", "Malformed outputs are rejected safely", "Unimplemented capabilities are excluded"],
    copyPrompt: "Use the Agent Buildprint: Portable Novel-to-Storyboard Pipeline.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/portable-novel-storyboard-pipeline/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/portable-novel-storyboard-pipeline",
    manifestUrl: "https://agent-buildprint.com/buildprints/portable-novel-storyboard-pipeline/package.json",
  },
  {
    slug: "portable-personal-agent-chat-os",
    title: "Portable Personal Agent Chat OS",
    creator: "Agent Buildprint",
    category: "Mapped Project",
    stack: [
      "Streaming chat",
      "Provider router",
      "Tools / Skills / MCP",
      "Memory and compaction",
      "Subagents",
      "Telemetry",
      "WebUI/API workbench"
    ],
    difficulty: "Advanced",
    summary: "Mapper OS phase-flow packet for building a clean-room, self-hosted personal agent chatbot OS with streaming chat, provider routing, tools, skills, MCP, memory, subagents, telemetry, and WebUI/API workbench surfaces.",
    promise: "A phase-flow Buildprint that lets a downstream agent implement a portable personal agent chatbot OS while keeping deterministic proof separate from live/external claims.",
    imageTone: "from-emerald-400/20 via-cyan-400/10 to-blue-500/20",
    includes: [
      "BUILDPRINT.md canonical entry",
      "01-questions.md setup questions",
      "02-project-setup.md architecture and operating contract",
      "blueprint.yaml machine contract",
      "03-phases/phase-index.yaml phase index",
      "03-phases/phase-flow.md orchestration protocol",
      "Phase files for storage, runtime, tools/MCP, memory/team/telemetry, safety, and WebUI/API",
      "04-evaluation.md evidence honesty gates",
      "05-evidence/evidence-ledger.schema.json",
      "Seed-only evidence ledger"
    ],
    risks: [
      "Overclaiming full Emperor Agent clone parity",
      "Unsafe shell/filesystem/network/browser tools",
      "Provider API drift",
      "Context truncation losing user instructions",
      "Skill injection bloat",
      "MCP timeout/security failures",
      "In-memory state being mistaken for durable persistence",
      "Telemetry hidden from UI",
      "Hosted auth, billing, publishing, media, or retrieval claims without proof"
    ],
    files: [
      "BUILDPRINT.md",
      "01-questions.md",
      "02-project-setup.md",
      "blueprint.yaml",
      "03-phases/phase-index.yaml",
      "03-phases/phase-flow.md",
      "04-evaluation.md",
      "05-evidence/evidence-ledger.schema.json",
      "05-evidence/evidence-ledger.jsonl"
    ],
    checks: [
      "Mapper selected-output structural check passes",
      "Executable packet starts from BUILDPRINT.md",
      "02-project-setup.md defines architecture, team model, execution authority, handoffs, AGENTS.md plan, quality gates, safety, assumptions, and phase start gate",
      "Every phase starts with the required implementation heading and routes through phase-flow artifacts",
      "Packaged evidence ledger is seed-only",
      "Runtime evidence belongs only in .buildprint/evidence/evidence-ledger.jsonl",
      "Evidence schema blocks blocked/missing/synthetic/partial rows from upgrading claims",
      "Publication copy prompt names the executable read order",
      "Legacy document sludge removed or reduced to compatibility spine files"
    ],
    copyPrompt: "Use the Portable Personal Agent Chat OS Mapper OS packet. Bootstrap exact snapshots with agb start https://agent-buildprint.com/buildprints/portable-personal-agent-chat-os/package.json . Then read BUILDPRINT.md, 01-questions.md, 02-project-setup.md, blueprint.yaml, 03-phases/phase-index.yaml, 03-phases/phase-flow.md, the active phase file, 04-evaluation.md, and 05-evidence/evidence-ledger.jsonl. Treat BUILDPRINT.md as canonical. Run every phase through 03-phases/phase-flow.md, create .buildprint/phase-runs/<phase-id>/ artifacts, read .buildprint/next-agent.md and current project AGENTS.md before phase work, and append runtime proof only to .buildprint/evidence/evidence-ledger.jsonl. Build the clean-room personal agent chatbot OS with streaming chat, provider routing, tools, skills, MCP adapter, memory/compaction, subagent delegation, token telemetry, WebUI/API workbench, and safety-gated tool policy. Use deterministic providers/tools by default. Do not claim Emperor Agent clone, exact UI parity, live provider parity, real MCP parity, shell/browser/network safety, production auth, billing, publishing, or hosted SaaS unless separately validated.",
    methodology: [
      "Setup gate",
      "Phase-flow execution",
      "Runtime evidence ledger",
      "Claim-safe validation"
    ],
    runtimeSpine: [
      "BUILDPRINT.md",
      "01-questions.md",
      "02-project-setup.md",
      "blueprint.yaml",
      "03-phases/phase-index.yaml",
      "03-phases/phase-flow.md",
      "03-phases/<active-phase>.md",
      "04-evaluation.md",
      "05-evidence/evidence-ledger.schema.json",
      ".buildprint/phase-runs/<phase-id>/proof.md",
      ".buildprint/evidence/evidence-ledger.jsonl"
    ],
    proofNotes: [
      "Mapper OS converted: Converted to executable-blueprint v5 phase-flow methodology with seed-only packaged evidence and honest runtime evidence rules.",
      "Converted to executable-blueprint v5 with phase-run artifacts and review contracts.",
      "Preserves personal agent OS behavior without copying source implementation or claiming exact clone parity.",
      "Runtime evidence is separated from seed evidence and blocked proof cannot upgrade claims.",
      "Shell, browser, network, filesystem writes, live providers, and real MCP are explicit approval/proof boundaries."
    ],
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/portable-personal-agent-chat-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/portable-personal-agent-chat-os/package.json",
  },
  {
    slug: "stripe-billing-extension",
    title: "Stripe Billing Extension",
    creator: "Agent Buildprint",
    category: "Integration",
    stack: ["TypeScript", "Stripe", "Webhooks", "SaaS"],
    difficulty: "Medium",
    summary: "Stripe Checkout, customer portal, verified webhooks, subscription state, entitlement guards, billing UI, and lifecycle tests.",
    promise: "Add SaaS billing to an existing product without missing webhook signatures, entitlement checks, or subscription lifecycle states.",
    imageTone: "from-emerald-400/20 via-cyan-400/10 to-blue-500/20",
    includes: ["Checkout sessions", "Customer portal", "Webhook verification", "Subscription state", "Entitlement guards"],
    risks: ["Webhook replay bugs", "Payment state drift", "Premium access without active subscription"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "README.md", "SPEC.md", "TARGET_STACK_ADAPTERS.md", "TEST_MATRIX.md", "proof/dist/src/billing/entitlements.js", "PLAN.md", "VALIDATION_TEMPLATE.md", "checks/acceptance.md"],
    checks: ["Webhook signatures are verified", "Portal access requires auth", "Entitlements check server state", "Lifecycle tests cover updates/cancellations"],
    copyPrompt: "Use the Agent Buildprint: Stripe Billing Extension.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/stripe-billing-extension/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/stripe-billing-extension",
    manifestUrl: "https://agent-buildprint.com/buildprints/stripe-billing-extension/package.json",
  },
  {
    slug: "superpowers-skill-methodology-harness",
    title: "Superpowers Skill Methodology Harness",
    creator: "Agent Buildprint",
    category: "Quality",
    stack: ["Node.js", "Agent skills", "Transcript evals", "Methodology"],
    difficulty: "Advanced",
    summary: "Portable harness that turns engineering process rules into executable agent behavior and transcript-backed verification.",
    promise: "Make coding agents load relevant skills, design before implementation, use TDD, delegate safely, and block completion without evidence.",
    imageTone: "from-red-400/20 via-orange-400/10 to-violet-500/20",
    includes: ["Skill lookup discipline", "Design approval gate", "TDD gate", "Subagent packets", "Transcript evals"],
    risks: ["Skipping process gates", "Copying upstream text", "Claiming official compatibility"],
    files: ["BOOTSTRAP_AND_ROUTING.md", "BUILDPRINT.md", "CONTRACTS.md", "SKILL_LIBRARY.md", "SOURCE_TRACE.md", "SPEC.md", "SUBAGENT_ORCHESTRATION.md", "README.md", "PLAN.md", "TEST_MATRIX.md", "VALIDATION_TEMPLATE.md", "checks/acceptance.md"],
    checks: ["Skills load before action", "Plans include exact paths/tests", "Review evidence blocks completion", "Transcript evals catch process drift"],
    copyPrompt: "Use the Agent Buildprint: Superpowers Skill Methodology Harness.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/superpowers-skill-methodology-harness/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/superpowers-skill-methodology-harness",
    manifestUrl: "https://agent-buildprint.com/buildprints/superpowers-skill-methodology-harness/package.json",
  },
];

export const categories = ['All', 'Product OS', 'Agent', 'Integration', 'Quality', 'Feature'] as const;

export function getBuildprint(slug: string) {
  return buildprints.find((buildprint) => buildprint.slug === slug);
}
