export type Buildprint = {
  slug: string;
  title: string;
  creator: string;
  category: 'Product OS' | 'Agent' | 'Integration' | 'Quality' | 'Feature';
  stack: string[];
  difficulty: 'Small' | 'Medium' | 'Advanced';
  summary: string;
  promise: string;
  imageTone: string;
  includes: string[];
  risks: string[];
  files: string[];
  checks: string[];
  copyPrompt: string;
  githubUrl: string;
  manifestUrl: string;
};

export const buildprints: Buildprint[] = [
  {
    slug: "auth-teams-rbac-os",
    title: "Auth, Teams & RBAC OS",
    creator: "Agent Buildprint",
    category: "Feature",
    stack: ["Auth", "Teams", "RBAC", "Multi-tenant SaaS", "Audit logs"],
    difficulty: "Advanced",
    summary: "Secure team accounts, memberships, roles, permissions, invites, audit logs, and tenant isolation around an existing auth provider.",
    promise: "Add Auth, Teams & RBAC without letting an agent rip out existing auth, fake frontend-only permissions, or miss tenant isolation.",
    imageTone: "from-violet-400/20 via-fuchsia-400/10 to-cyan-500/20",
    includes: ["Auth forensics", "Tenant boundary map", "Permission engine", "Invite lifecycle", "Audit log"],
    risks: ["Frontend-only authorization", "Cross-tenant data leaks", "Self-escalation or last-owner loss"],
    files: ["BUILDPRINT.md", "SPEC.md", "CONTRACTS.md", "RBAC_MATRIX.md", "API_ROUTES.md", "UI_FLOWS.md", "TEST_MATRIX.md"],
    checks: ["Phase 00 forensics must complete first", "Permission engine denies by default", "Every team-scoped route has direct API auth tests", "Invites and role changes emit redacted audit events"],
    copyPrompt: "Use the Agent Buildprint: Auth, Teams & RBAC OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/auth-teams-rbac-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine. Do Phase 00 auth forensics and tenant research before coding. Reuse existing auth by default, enforce permissions server-side, and do not claim completion while any team-scoped route lacks direct authorization tests.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/auth-teams-rbac-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/auth-teams-rbac-os/package.json",
  },
  {
    slug: "ai-influencer-os",
    title: "OpenClaw AI Influencer OS",
    creator: "Agent Buildprint",
    category: "Product OS",
    stack: ["OpenClaw", "Telegram", "Wavespeed", "OpenRouter", "Docker"],
    difficulty: "Advanced",
    summary: "Persona memory, social drafting, image generation, approval gates, and secured browser publishing handoff for an AI influencer runtime.",
    promise: "Bootstrap a full OpenClaw-based AI Influencer OS without letting an agent collapse it into a generic chatbot or scheduler.",
    imageTone: "from-pink-400/20 via-fuchsia-400/10 to-cyan-500/20",
    includes: ["Persona + memory state", "Wavespeed image workflow", "Grounded social drafts", "Manager audit", "Secured browser handoff"],
    risks: ["Auto-publishing by default", "Unsafe public/private media handling", "Unauthenticated noVNC exposure"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "DEFAULT_PRESET.md", "PLAN.md", "SPEC.md", "TEST_MATRIX.md", "VALIDATION_TEMPLATE.md"],
    checks: ["Mock tests make no external API calls", "Media policy gates return structured blocks", "Publishing defaults to approval/manual mode", "Runtime command and files are present"],
    copyPrompt: "Use the Agent Buildprint: OpenClaw AI Influencer OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/ai-influencer-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/ai-influencer-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/ai-influencer-os/package.json",
  },
  {
    slug: "automated-ai-blog-os",
    title: "Automated AI Blog OS",
    creator: "Agent Buildprint",
    category: "Product OS",
    stack: ["Astro/MDX", "Markdown", "SEO", "Approval queue", "Scheduler"],
    difficulty: "Advanced",
    summary: "Research scanning, idea scoring, content memory, draft generation, SEO validation, approval queue, and scheduled publishing.",
    promise: "Give a coding agent the full operating contract for a useful AI blog pipeline that does not skip SEO, approval, or stale-content audits.",
    imageTone: "from-lime-400/20 via-emerald-400/10 to-cyan-500/20",
    includes: ["Research scanner", "Idea scorer", "Content memory", "SEO validator", "Approval queue"],
    risks: ["Publishing without approval", "Unsupported claims", "SEO/build checks skipped"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "DEFAULT_PRESET.md", "PLAN.md", "SPEC.md", "TEST_MATRIX.md", "VALIDATION_TEMPLATE.md"],
    checks: ["Drafts cite source/evidence state", "SEO/build validator runs before publish", "Approval gate blocks external publishing", "Manager audit catches stale work"],
    copyPrompt: "Use the Agent Buildprint: Automated AI Blog OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/automated-ai-blog-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/automated-ai-blog-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/automated-ai-blog-os/package.json",
  },
  {
    slug: "buildprint-mapper-os",
    title: "Buildprint Mapper OS",
    creator: "Agent Buildprint",
    category: "Quality",
    stack: ["Any repo", "Static analysis", "LLM review", "Evidence maps"],
    difficulty: "Advanced",
    summary: "Map an existing repo into an evidence-backed Buildprint package with scope, contracts, risks, checks, and handoff prompts.",
    promise: "Turn a real codebase into an AI-readable architecture contract so agents extend it from evidence instead of guesses.",
    imageTone: "from-sky-400/20 via-teal-400/10 to-lime-400/20",
    includes: ["Repository census", "Evidence-backed map", "Scope decision gate", "Buildprint extraction", "Clean-room reversal"],
    risks: ["Secret leakage", "Overconfident inference", "Including unsupported capabilities"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "PLAN.md", "README.md", "SPEC.md", "TEST_MATRIX.md", "VALIDATION_TEMPLATE.md"],
    checks: ["No secret values copied", "Low-confidence areas become questions", "Every included capability has validation", "Reversal attempt verifies usability"],
    copyPrompt: "Use the Agent Buildprint: Buildprint Mapper OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/buildprint-mapper-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/buildprint-mapper-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/buildprint-mapper-os/package.json",
  },
  {
    slug: "complete-agent-skills-evaluation-os",
    title: "Complete Agent Skills Evaluation OS",
    creator: "Agent Buildprint",
    category: "Quality",
    stack: ["Node.js", "Fixtures", "Eval harness", "CI"],
    difficulty: "Advanced",
    summary: "Offline deterministic evals for skills, agent setup contracts, commands, hooks, routers, subagents, and workflow rules.",
    promise: "Prove whether an agent setup is installed, discoverable, useful, safe, reproducible, and worth its context cost.",
    imageTone: "from-violet-400/20 via-indigo-400/10 to-cyan-500/20",
    includes: ["Setup snapshot", "Static lint", "Skill unit evals", "Transcript invariants", "Scorecard"],
    risks: ["Live-provider false positives", "Undiscoverable skills", "Unsafe multi-agent execution"],
    files: ["ACTIVATION_EVALS.md", "BUILDPRINT.md", "CONTRACTS.md", "E2E_TASK_BENCH.md", "LOADOUT_INVENTORY.md", "MULTI_AGENT_SAFETY.md", "SAFETY_POLICY.md"],
    checks: ["Offline fixtures only by default", "Scorecard produces evidence", "Process invariants are asserted", "Live adapters require separate acceptance"],
    copyPrompt: "Use the Agent Buildprint: Complete Agent Skills Evaluation OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/complete-agent-skills-evaluation-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/complete-agent-skills-evaluation-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/complete-agent-skills-evaluation-os/package.json",
  },
  {
    slug: "perfect-rag-retrieval-os",
    title: "Perfect RAG / Retrieval OS",
    creator: "Agent Buildprint",
    category: "Agent",
    stack: ["TypeScript", "Hybrid retrieval", "Reranking", "Citations", "Evals"],
    difficulty: "Advanced",
    summary: "Permission-safe hybrid retrieval, reranking, context packing, grounded answers, refusals, traces, and repeatable evals.",
    promise: "Build serious RAG beyond “vector DB + prompt” with measurable retrieval quality and citation-grounded answer behavior.",
    imageTone: "from-blue-400/20 via-cyan-400/10 to-emerald-500/20",
    includes: ["Hybrid first-stage retrieval", "Permission filtering", "Reranking", "Grounded generation", "Eval report"],
    risks: ["Permission leakage", "Uncited hallucinations", "Weak retrieval metrics"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "EVAL_HARNESS.md", "README.md", "SPEC.md", "TARGET_STACK_ADAPTERS.md", "TEST_MATRIX.md"],
    checks: ["Refuses insufficient evidence", "Citations point to retrieved chunks", "Permission filters hide restricted chunks", "Eval reports recall/MRR behavior"],
    copyPrompt: "Use the Agent Buildprint: Perfect RAG / Retrieval OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/perfect-rag-retrieval-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/perfect-rag-retrieval-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/perfect-rag-retrieval-os/package.json",
  },
  {
    slug: "portable-ai-shorts-production-studio",
    title: "Portable AI Shorts Production Studio",
    creator: "Agent Buildprint",
    category: "Product OS",
    stack: ["Video", "Gemini research", "Voice", "FFmpeg", "Provider adapters"],
    difficulty: "Advanced",
    summary: "A portable studio for vertical UGC-style marketing video drafts from a product URL or manual product description.",
    promise: "Build an honest AI shorts production pipeline with provider boundaries, privacy gates, generation stages, and draft-status clarity.",
    imageTone: "from-orange-400/20 via-rose-400/10 to-purple-500/20",
    includes: ["Product analysis", "Viral script generation", "Voice/actor choices", "Provider adapters", "FFmpeg composition"],
    risks: ["Publishing private media", "Provider key mishandling", "Claiming draft videos are production-ready"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "PARITY_CLAIMS.md", "PLAN.md", "QA_PLAN.md", "SOURCE_TRACE.md", "SPEC.md"],
    checks: ["Privacy/publication gates are explicit", "Provider paths can run in mock mode", "Status polling exposes failures", "Final exports are gated"],
    copyPrompt: "Use the Agent Buildprint: Portable AI Shorts Production Studio.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/portable-ai-shorts-production-studio/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/portable-ai-shorts-production-studio",
    manifestUrl: "https://agent-buildprint.com/buildprints/portable-ai-shorts-production-studio/package.json",
  },
  {
    slug: "portable-durable-agent-graph-runtime",
    title: "Portable Durable Agent Graph Runtime",
    creator: "Agent Buildprint",
    category: "Agent",
    stack: ["TypeScript", "Graph runtime", "Checkpoints", "Streams", "Interrupts"],
    difficulty: "Advanced",
    summary: "Dependency-light runtime for typed state, graph nodes, conditional edges, checkpointing, streaming, interrupts, and resume.",
    promise: "Create a portable LangGraph-like mental model without runtime lock-in or hidden framework dependencies.",
    imageTone: "from-cyan-400/20 via-indigo-400/10 to-purple-500/20",
    includes: ["Typed state schema", "Graph builder", "Checkpoint saver", "Interrupt/resume", "Streaming invoke"],
    risks: ["Fake durability", "Unclear state reducers", "Side effects without checkpoints"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "PARITY_CLAIMS.md", "PLAN.md", "QA_PLAN.md", "README.md", "SOURCE_TRACE.md"],
    checks: ["Compile validation catches bad routes", "Checkpoint interfaces are explicit", "Interrupt resume is tested", "No heavyweight graph dependency required"],
    copyPrompt: "Use the Agent Buildprint: Portable Durable Agent Graph Runtime.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/portable-durable-agent-graph-runtime/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/portable-durable-agent-graph-runtime",
    manifestUrl: "https://agent-buildprint.com/buildprints/portable-durable-agent-graph-runtime/package.json",
  },
  {
    slug: "portable-novel-storyboard-pipeline",
    title: "Portable Novel-to-Storyboard Pipeline",
    creator: "Agent Buildprint",
    category: "Product OS",
    stack: ["Story pipeline", "Mock providers", "Storyboard XML", "Canvas QA"],
    difficulty: "Advanced",
    summary: "Import chapters, extract events, adapt scripts, create assets, generate storyboard panels, validate XML, and preview without fake success states.",
    promise: "Build a deterministic novel-to-storyboard pipeline that agents can implement end-to-end before expanding into live providers.",
    imageTone: "from-amber-400/20 via-fuchsia-400/10 to-blue-500/20",
    includes: ["Chapter import", "Event extraction", "ScriptAgent stages", "Asset extraction", "Storyboard validation"],
    risks: ["Malformed XML corrupting state", "Placeholder controls", "Live-provider claims without gates"],
    files: ["AGENT_HANDOFF.md", "AGENT_PROMPT_PACK.md", "ASYNC_JOB_MODEL.md", "BROWSER_QA_SCENARIOS.md", "BUILDPRINT.md", "CONTRACTS.md", "HEAD_TO_FOOT_QA.md"],
    checks: ["Default CI uses mock/no-network providers", "3 fixture chapters complete successfully", "Malformed outputs are rejected safely", "Unimplemented capabilities are excluded"],
    copyPrompt: "Use the Agent Buildprint: Portable Novel-to-Storyboard Pipeline.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/portable-novel-storyboard-pipeline/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/portable-novel-storyboard-pipeline",
    manifestUrl: "https://agent-buildprint.com/buildprints/portable-novel-storyboard-pipeline/package.json",
  },
  {
    slug: "portable-personal-agent-chat-os",
    title: "Portable Personal Agent Chat OS",
    creator: "Agent Buildprint",
    category: "Agent",
    stack: ["Self-hosted agent", "Streaming UI", "Tools", "Skills", "Memory"],
    difficulty: "Advanced",
    summary: "Self-hosted personal agent chatbot with provider routing, streaming events, policy-gated tools, skills, memory, teams, and telemetry.",
    promise: "Build the control surface for a local personal agent runtime with explicit policies, memory, tools, subagents, and WebUI/API boundaries.",
    imageTone: "from-emerald-400/20 via-cyan-400/10 to-blue-500/20",
    includes: ["Provider router", "Streaming agent loop", "Tool/skill registry", "Memory context", "Team bus telemetry"],
    risks: ["Unsafe tool execution", "Memory leakage", "Opaque token costs"],
    files: ["AGENT_RUNTIME.md", "BUILDPRINT.md", "CONTRACTS.md", "HEAD_TO_FOOT_QA.md", "MEMORY_CONTEXT.md", "PARITY_CLAIMS.md", "PLAN.md"],
    checks: ["Tools pass through policy mediation", "Memory assembly order is explicit", "Streaming events cover failures", "Token telemetry is visible"],
    copyPrompt: "Use the Agent Buildprint: Portable Personal Agent Chat OS.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/portable-personal-agent-chat-os/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/portable-personal-agent-chat-os",
    manifestUrl: "https://agent-buildprint.com/buildprints/portable-personal-agent-chat-os/package.json",
  },
  {
    slug: "stripe-billing-extension",
    title: "Stripe Billing Extension",
    creator: "Agent Buildprint",
    category: "Integration",
    stack: ["TypeScript", "Stripe", "Webhooks", "SaaS"],
    difficulty: "Medium",
    summary: "Stripe Checkout, customer portal, verified webhooks, subscription state, entitlement guards, billing UI, and lifecycle tests.",
    promise: "Add SaaS billing to an existing product without missing webhook signatures, entitlement checks, or subscription lifecycle states.",
    imageTone: "from-emerald-400/20 via-cyan-400/10 to-blue-500/20",
    includes: ["Checkout sessions", "Customer portal", "Webhook verification", "Subscription state", "Entitlement guards"],
    risks: ["Webhook replay bugs", "Payment state drift", "Premium access without active subscription"],
    files: ["BUILDPRINT.md", "CONTRACTS.md", "README.md", "SPEC.md", "TARGET_STACK_ADAPTERS.md", "TEST_MATRIX.md", "proof/dist/src/billing/entitlements.js"],
    checks: ["Webhook signatures are verified", "Portal access requires auth", "Entitlements check server state", "Lifecycle tests cover updates/cancellations"],
    copyPrompt: "Use the Agent Buildprint: Stripe Billing Extension.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/stripe-billing-extension/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/stripe-billing-extension",
    manifestUrl: "https://agent-buildprint.com/buildprints/stripe-billing-extension/package.json",
  },
  {
    slug: "superpowers-skill-methodology-harness",
    title: "Superpowers Skill Methodology Harness",
    creator: "Agent Buildprint",
    category: "Quality",
    stack: ["Node.js", "Agent skills", "Transcript evals", "Methodology"],
    difficulty: "Advanced",
    summary: "Portable harness that turns engineering process rules into executable agent behavior and transcript-backed verification.",
    promise: "Make coding agents load relevant skills, design before implementation, use TDD, delegate safely, and block completion without evidence.",
    imageTone: "from-red-400/20 via-orange-400/10 to-violet-500/20",
    includes: ["Skill lookup discipline", "Design approval gate", "TDD gate", "Subagent packets", "Transcript evals"],
    risks: ["Skipping process gates", "Copying upstream text", "Claiming official compatibility"],
    files: ["BOOTSTRAP_AND_ROUTING.md", "BUILDPRINT.md", "CONTRACTS.md", "SKILL_LIBRARY.md", "SOURCE_TRACE.md", "SPEC.md", "SUBAGENT_ORCHESTRATION.md"],
    checks: ["Skills load before action", "Plans include exact paths/tests", "Review evidence blocks completion", "Transcript evals catch process drift"],
    copyPrompt: "Use the Agent Buildprint: Superpowers Skill Methodology Harness.\n\nBootstrap it with `agb start https://agent-buildprint.com/buildprints/superpowers-skill-methodology-harness/package.json ./my-build` or inspect the GitHub folder. Follow BUILDPRINT.md as the authority spine, read the supporting contracts/checks before implementation, preserve the stated non-goals and safety gates, and do not claim completion until the included validation checks pass.",
    githubUrl: "https://github.com/DomEscobar/agent-buildprint/tree/main/buildprints/superpowers-skill-methodology-harness",
    manifestUrl: "https://agent-buildprint.com/buildprints/superpowers-skill-methodology-harness/package.json",
  },
];

export const categories = ['All', 'Product OS', 'Agent', 'Integration', 'Quality', 'Feature'] as const;

export function getBuildprint(slug: string) {
  return buildprints.find((buildprint) => buildprint.slug === slug);
}
